### ISSUE TITLE
speclite installs extra scripts in bin/

### ISSUE THREAD

**Issue by weaverba137** [desihub/speclite#16]
I just installed speclite at NERSC with desiInstall, which is just a wrapper on python setup.py install.  A number of command-line scripts appeared in the bin directory, in addition to the speclite_benchmark script.  See /global/project/projectdirs/desi/software/cori/speclite/v0.4/bin.

**Comment by dkirkby** [comment]
Yikes!  Do you have some advice on how to debug this?  For the record, the following are installed into bin currently:
```
fits2bitmap  fitscheck  fitsdiff  fitsheader  fitsinfo  samp_hub  speclite_benchmark  volint  wcslint
```
Here is the output from `python setup.py --verbose --dry-run install_scripts`:
```
running install_scripts
running egg_info
writing requirements to speclite.egg-info/requires.txt
writing speclite.egg-info/PKG-INFO
writing top-level names to speclite.egg-info/top_level.txt
writing dependency_links to speclite.egg-info/dependency_links.txt
writing entry points to speclite.egg-info/entry_points.txt
reading manifest file 'speclite.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.c' under directory '*.pyx'
warning: no files found matching '*.pxd' under directory '*.pyx'
warning: no files found matching '*' under directory 'scripts'
no previously-included directories found matching 'build'
warning: no previously-included files matching '*.o' found anywhere in distribution
writing manifest file 'speclite.egg-info/SOURCES.txt'
Installing speclite_benchmark script to /Users/david/anaconda/bin
```
I don't see any of these interloper scripts mentioned in any of the files under `speclite.egg-info` or in `astropy_helpers/setup.cfg`.

**Comment by weaverba137** [comment]
The extra scripts are the same scripts that are normally installed by astropy itself.

Still looking...

**Comment by weaverba137** [comment]
Aha, I thought this problem seemed familiar:  https://github.com/astropy/package-template/issues/111

Unfortunately no resolution as yet.

**Comment by dkirkby** [comment]
My reading of pypa/setuptools#395 is that this is considered expected behavior and will not be fixed.  Do you agree @weaverba137?

**Comment by weaverba137** [comment]
I agree that this is expected behavior when running `python setup.py install`.  However, what is the expected behavior when running `pip install`?  My current belief is that `pip install` is the way forward.  And in any case, we're pip installing into the desiconda package.

**Comment by weaverba137** [comment]
In a recent test with `pip install` (with the same options that `desiInstall` uses) and tag `v0.17`, only the expected script `speclite_benchmark` was installed in `bin/`. Closing.
