### ISSUE TITLE
speclite.filters.get_ab_maggies alters input wavelength array?

### ISSUE THREAD

**Issue by moustakas** [desihub/speclite#34]
In https://github.com/imcgreer/simqso/issues/20 @imcgreer identified an issue in which the `speclite.filters.get_ab_maggies` method appears to alter the input wavelength array.  See, specifically, [this comment](https://github.com/imcgreer/simqso/issues/20#issuecomment-350386964) and the subsequent one.  

However, I can't reproduce this with a MWE (see below).  Do you have any thoughts?

```python
import numpy as np
from speclite import filters
ff = filters.load_filters('decam2014-r')
wave = np.linspace(3000., 11000., 100)
wave2 = wave.copy()
flux = np.ones_like(wave)
_ = ff.get_ab_maggies(flux, wave)
assert(np.all(wave == wave2))
```

**Comment by dkirkby** [comment]
[These lines](https://github.com/dkirkby/speclite/blob/master/speclite/filters.py#L1329) will modify the input wave array under certain conditions:
 - `validate_wavelength_array()` does not need to make a copy, e.g., to strip units or convert from python to numpy array.
 - the filter response is zero for some of the wavelengths in the input array.

However, I am also unable to reproduce this with a MWE, so there's something I still don't understand.  For moving forwards with simqso, I suggest that you use the copy() for now, until I can spend more time getting to the bottom of this.

**Comment by segasai** [comment]
Hi, 

This code  will consistently corrupt the wavelength array 
```
import speclite.filters
import numpy as np
filters = speclite.filters.load_filters('gaiadr2-BP', 'gaiadr2-RP',
                                        'gaiadr2-G')
waves = np.arange(3000, 11000, 0.11)
waves0 = waves.copy()
flux = waves * 1.
filters[0].get_ab_magnitude(flux, waves)
print(np.nonzero(waves != waves0), waves[2249], waves0[2249])
```
Output:
(array([ 2249, 40932]),) 3247.4999999999995 3247.3900000002864

IMO validate_wavelength_array() must make a copy even at a performance cost, because 
the current behaviour is dangerous as it leads to silent corruption (i've encountered this bug while working on stdstars DESI script)

 S

**Comment by dkirkby** [comment]
Thanks for this @segasai.   I will take care of this but presumably you can copy your wavelength array in the stdstars script so this is not blocking you?

**Comment by segasai** [comment]
Yes, that's what I did for the time being. 
I just was suggesting that given the danger of the bug, it may be worth putting a stopgap copy() inside validate_wavelength_array() now before coming with a proper fix, but that's just IMO.

**Comment by dkirkby** [comment]
No reason. Are you willing to make a PR?

**Comment by weaverba137** [comment]
Yes, I intend to make a general clean-up of speclite in preparation for Kibo. See also my email on `desi-data`.
