### ISSUE TITLE
Euclid throughputs

### ISSUE THREAD

**Issue by fjaviersanchez** [desihub/speclite#47]
I just found the latest current best estimate of Euclid's filters for VIS here:
http://euclid.esac.esa.int/epdb/db/SC456Draft/SC456Draft/SpaceSegment.PLM.PLMTransmissionVISCBENominalEOL.table

And for NISP here:
http://euclid.esac.esa.int/epdb/db/SC456Draft/SC456Draft/SpaceSegment.PLM.PLMTransmissionNISPCBENominalEOL.table

I still have to decode what each column means but, as soon as I do so, I'll proceed to add them to speclite.

**Comment by fjaviersanchez** [comment]
So the different columns correspond to different points in the focal-plane
> "9 field points (F1 to F9) Field Points F(Xangel, Yangle) in degrees: F1: (0, 0.47014) F2: (0, 0.82174) F3: (0, 1.16949) F4: (0.39308, 0.46968) F5: (0.39196, 0.82094) F6: (0.39026, 1.16838) F7: (-0.39308, 0.46968) F8: (-0.39196, 0.82094) F9: (-0.39026, 1.16838)", 

The throughputs are the current best estimate at the end of life. I am going to add the throughputs corresponding to F1.

**Comment by fjaviersanchez** [comment]
The H, J and Y filters for NISP are here: http://euclid.esac.esa.int/epdb/db/SC456Draft/SC456Draft/SpaceSegment.Instrument.NISP.NISPHTransmissionCBENominalEOL.table
http://euclid.esac.esa.int/epdb/db/SC456Draft/SC456Draft/SpaceSegment.Instrument.NISP.NISPJTransmissionCBENominalEOL.table
http://euclid.esac.esa.int/epdb/db/SC456Draft/SC456Draft/SpaceSegment.Instrument.NISP.NISPYTransmissionCBENominalEOL.table

**Comment by weaverba137** [comment]
This was apparently fixed by #48.  Reopen if that's wrong.
