### ISSUE TITLE
Is speclite.readthedocs.io updated?

### ISSUE THREAD

**Issue by weaverba137** [desihub/speclite#57]
When we moved speclite, did the configuration of https://speclite.readthedocs.io/en/latest/ get updated?

**Comment by dkirkby** [comment]
I just updated the repo URL in the RTD config.  Are there any other changes you think we need?

**Comment by weaverba137** [comment]
I just visited https://speclite.readthedocs.io/en/latest/, and it still says that it was last updated in 2018.  I'm guessing that automated builds are broken.

**Comment by dkirkby** [comment]
Ok, I just triggered a manual build of "latest", which dies as expected. Log is at https://readthedocs.org/api/v2/build/11541017.txt

**Comment by weaverba137** [comment]
Looks like you need to change the build to Python 3.

**Comment by dkirkby** [comment]
Good catch.   Fixed, and now the error looks like a legacy astropy issue: https://readthedocs.org/projects/speclite/builds/11541086/

**Comment by dkirkby** [comment]
I will add you as an RTD maintainer if you send me your username.

**Comment by weaverba137** [comment]
https://speclite.readthedocs.io/en/latest/ is building successfully again.  Had to add `sphinx-astropy` package.
