### ISSUE TITLE
AB magnitudes not correctly predicted

### ISSUE THREAD

**Issue by redeaglekr** [desihub/speclite#58]
Hi, 

I am using speclite for one of my project. I wanted check whether speclite's get_ab_magnitude function correctly predicts the magnitudes, as given in SDSS object explorer. So I downloaded a fits spectra of an object at RA = 190.269777714638  Dec = 37.6625678269159. The wavelength axis was not covering the u - band and z - band range, so I padded the spectrum and tried to get the magnitudes using get_ab_magnitudes. Unfortunately, I didn't got the same values. Could you please help me?

Result : [(22.24537585, 21.73756632, 21.54939652, 21.23126276, 20.98593275)]

[https://skyserver.sdss.org/dr14/en/tools/explore/summary.aspx?ra=190.269777714638%09&dec=37.6625678269159](url) object

**Comment by dkirkby** [comment]
Padding of u and z will underestimate the flux and should only be used when you know the padded wavelengths have no flux.

For gri, you are comparing synthetic magnitudes (i.e., derived from the spectra) with magnitudes from SDSS imaging. I am not sure what level of agreement to expect, but you cannot compare these directly.

The best test would be to compare with SPECTROSYNFLUX calculated from the spectra by the eBOSS pipeline.  These are available in several places, e.g. the spAll catalog described here:

  https://data.sdss.org/datamodel/files/BOSS_SPECTRO_REDUX/RUN2D/spAll.html

That might still not give identical results, depending on how it uses IVAR weights, but it should be close.
