### ISSUE TITLE
Padding method not propagated for filter group

### ISSUE THREAD

**Issue by dkirkby** [desihub/speclite#64]
Calling `pad_spectrum`  on a `FilterSequence` does not propagate a non-default `method` arg when `pad_spectrum` is called on the individual filters.  The solution is to add `method`  below:
```
        for response in sorted_responses:
            padded_spectrum, padded_wavelength = response.pad_spectrum(
                padded_spectrum, padded_wavelength, method)
```
Thanks to Anand for reporting this.

**Comment by weaverba137** [comment]
@araichoor @dkirkby, this seems like a trivial issue to fix. Is there a hidden reason why there is no PR associated with this?

**Comment by dkirkby** [comment]
No, we just need someone to make the PR and test it.

**Comment by weaverba137** [comment]
Will do.
