### ISSUE TITLE
accommodating a band_shifted filter curve?

### ISSUE THREAD

**Issue by moustakas** [desihub/speclite#69]
@dkirkby how straightforward would it be to add a `band_shift` optional input when calling `speclite.filters.load_filters` or as a (vector) input to the convolution methods like `filters.get_ab_maggies`?

I'm trying to implement https://github.com/desihub/fastspecfit/issues/43.

**Comment by dkirkby** [comment]
I am not sure what you mean by band shifted.  Does this boil down to multiplying the wavelengths in a filter table by a constant factor when it is read in?

**Comment by moustakas** [comment]
Looks like this functionality was always present--
  https://speclite.readthedocs.io/en/latest/api.html#shifted-filters
Closing!
