### ISSUE TITLE
Citation instructions?

### ISSUE THREAD

**Issue by chrislintott** [desihub/speclite#75]
Hi

Just came by to say it would be great if you could provide guidance to people trying to work out how to cite speclite. If there's nothing in the literature, I'd be happy to publish a brief Research Note (https://iopscience.iop.org/journal/2515-5172) if that's helpful.

**Comment by dkirkby** [comment]
Thanks for the suggestion @chrislintott.  The easiest would be a citable zenodo DOI like [this](https://zenodo.org/record/4566008#.YjYnWJrMJqs).  Would that work for your purposes?

**Comment by dkirkby** [comment]
I should also add a CITATION.cff file now that those are [supported](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files).

**Comment by augustfly** [comment]
Echoing Chris: I was trying to check some references in a submission and it took a long time to find this! Perhaps add the DOI to the main-page ReadMe and update the Zenodo title and/or new version? I'll let this speclite user know about the current DOI though.

**Comment by dkirkby** [comment]
@dylanagreen and I just created a DOI for the latest tag and added citation instructions to the README.  For reference, the DOI is 10.5281/zenodo.7734526

**Comment by weaverba137** [comment]
The citation is visible in the README file.  If there are other specific issues with the citation, please open a new ticket.
